### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by FrankvdStam** [neimex23/HitCounterManager#3]
Hi,

Good to see soulsplitter used in other projects, reuse is the reason why SoulMemory and SoulSplitter are in separate projects.
However, you seem to have forgotten to include the license of one of SoulSplitter 's contributors.

Please include CapitaineToinon's license: https://github.com/FrankvdStam/SoulSplitter/blob/main/CapitaineToinon%20-%20COPYING

**Comment by neimex23** [comment]
Hello,

Thnx for your amazing work im added Some Mentions In ThirdPartyLicenseReadme, i added CapitaineToinon's license as you asked me and their names on Licenses. Tell Me if i forget any mention, sorry about drawbacks im really learning about all of Licenses how to mentions, how to used, what i can and cant to do depending Licenses is a headache but understandable.

Regards

**Comment by FrankvdStam** [comment]
Thanks!
